### ISSUE TITLE
Change settings on the Fly 

### ISSUE THREAD

**Issue by polyphia** [WeizhaoT/geth_peri#2]
Hi 

Is there a way to change the peri status without restarting node ? Doesn't it just preload all the variables from the json ?

If node is still syncing it's not good to have it active .

Thanks

**Comment by WeizhaoT** [comment]
Hi, 

I'm sorry, but it cannot be edited in our implementation on the fly. We recommended you to turn it off during sync, and turn it back on after sync. 

It is possible to implement this feature, though. Please feel free to edit the console that accepts javascript commands on the fly.
